export const RECEIVE_AE_TIME_DATA = 'RECEIVE_AE_TIME_DATA';
export const RECEIVE_RECALL_TIME_DATA = 'RECEIVE_RECALL_TIME_DATA';
export const SELECT_TAB = 'SELECT_TAB';
export const RESET_TAB = 'RESET_TAB';
export const RECEIVE_RECORD = 'RECEIVE_RECORD';
