export const RECEIVE_AE_TIME_DATA = 'RECEIVE_AE_TIME_DATA';
export const RECEIVE_RECALL_TIME_DATA = 'RECEIVE_RECALL_TIME_DATA';
export const RECEIVE_RECALL_STATUS = 'RECEIVE_RECALL_STATUS';
export const RECEIVE_RECALL_CLASSES = 'RECEIVE_RECALL_CLASSES';
export const SELECT_TAB = 'SELECT_TAB';
export const RECEIVE_RECORD = 'RECEIVE_RECORD';
